<?php  


#########################################################################
class node_config {
  var $prefix;
  var $suffix;
  
  var $nodes;							// dhcpd.conf node 列表
  var $leases;						// dpchd.lease 的 lease 列表
  
  var $right_prefix;			// 权限文件前缀
  var $right_suffix;			// 权限文件后缀
  var $defaultrights;			// 默认权限
  var $unknownrights;			// 无法识别的权限
  
  var $originmac;					// 原始mac记录

static function __set_state($array) 
{
	$tmp = new node_config();
	$tmp->prefix = $array['prefix'];
	$tmp->suffix=  $array['suffix'];
	$tmp->nodes=   $array['nodes'];

	$tmp->leases=$array['leases'];			
	$tmp->right_prefix=$array['right_prefix'];		
	$tmp->right_suffix=$array['right_suffix'];		
	$tmp->defaultrights=$array['defaultrights'];		
	$tmp->unknownrights=$array['unknownrights'];		

	$tmp->originmac= $array['originmac'];;					// 原始mac记录



	return $tmp;
}
}

#########################################################################
class node {
	var $mac;								// mac 地址
	var $active;						// 记录是否有效
	
	var $deny;							// 是否禁止
	var $fixedip;						// 是否固定IP地址
	var $ipaddr;						// IP 地址
	
	var $subnet;						// 子网段
	
	var $terminal_default;	// 是否使用默认终端配置
	var $say;								// 提示信息
	var $timeout;						// 超时
	var $default;						// 默认启动选项
	var $allowchoose;				// 是否允许选择启动选项
	var $labels;						// 可选择的启动选项
	
	var $right_default;			// 是否使用默认权限
	var $rights;						// 权限
	
	var $filename;					// 配置文件名，IP地址16进制大写

	static function __set_state($array) 
	{
		$tmp = new node();

		$tmp->mac=$array['mac'];				
		$tmp->active=$array['active'];			
		$tmp->deny=$array['deny'];				
		$tmp->fixedip=$array['fixedip'];			
		$tmp->ipaddr=$array['ipaddr'];			
		$tmp->subnet=$array['subnet'];			
		$tmp->terminal_default=$array['terminal_default'];	
		$tmp->say=$array['say'];				
		$tmp->timeout=$array['timeout'];			
		$tmp->default=$array['default'];			
		$tmp->allowchoose=$array['allowchoose'];		
		$tmp->labels=$array['labels'];			
		$tmp->right_default=$array['right_default'];		
		$tmp->rights=$array['rights'];			
		$tmp->filename=$array['filename'];			

		return $tmp;
	}

}

$a=node_config::__set_state(array(
   'prefix' => 'option space PXE;
option PXE.mtftp-ip               code 1 = ip-address;  
option PXE.mtftp-cport            code 2 = unsigned integer 16;
option PXE.mtftp-sport            code 3 = unsigned integer 16;
option PXE.mtftp-tmout            code 4 = unsigned integer 8;
option PXE.mtftp-delay            code 5 = unsigned integer 8;
option PXE.discovery-control      code 6 = unsigned integer 8;
option PXE.discovery-mcast-addr   code 7 = ip-address;

allow unknown-clients;
allow bootp;
allow booting;
option subnet-mask 255.255.255.0;
option broadcast-address 172.16.10.255;
option domain-name "qianlong";
option routers 	172.16.10.1;
option vendor-class-identifier "PXEClient";
vendor-option-space PXE; 
option PXE.mtftp-ip 0.0.0.0;
	
ddns-update-style none;
	
subnet 172.16.10.0  netmask 255.255.255.0 {
	      	range dynamic-bootp 172.16.10.20 172.16.10.250;
default-lease-time 1600;
max-lease-time 3200;
next-server 172.16.10.199;
filename "pxelinux.0";
	
}

;qianqian63
;qianqian27
;qianqian66
;qianqian71
',
   'suffix' => NULL,
   'nodes' => 
  array (
    '00:0C:29:42:AB:8E' => 
    node::__set_state(array(
       'mac' => '00:0C:29:42:AB:8E',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.12',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100A0C',
    )),
    '00:16:3E:5D:C7:9F' => 
    node::__set_state(array(
       'mac' => '00:16:3E:5D:C7:9F',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.227',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AE3',
    )),
    '00:0C:29:77:08:DC' => 
    node::__set_state(array(
       'mac' => '00:0C:29:77:08:DC',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.247',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AF7',
    )),
    'DC:0E:F9:82:D5:F6' => 
    node::__set_state(array(
       'mac' => 'DC:0E:F9:82:D5:F6',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.210',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AD2',
    )),
    'DC:0E:BB:BB:01:08' => 
    node::__set_state(array(
       'mac' => 'DC:0E:BB:BB:01:08',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.104',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100A68',
    )),
    '52:54:00:7E:3C:07' => 
    node::__set_state(array(
       'mac' => '52:54:00:7E:3C:07',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.200',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AC8',
    )),
    '00:0C:29:DC:B8:85' => 
    node::__set_state(array(
       'mac' => '00:0C:29:DC:B8:85',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.108',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100A6C',
    )),
    '00:19:E0:75:0C:08' => 
    node::__set_state(array(
       'mac' => '00:19:E0:75:0C:08',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.229',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AE5',
    )),
    '00:0C:29:E6:5F:0D' => 
    node::__set_state(array(
       'mac' => '00:0C:29:E6:5F:0D',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.226',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AE2',
    )),
    '08:00:27:27:E7:FA' => 
    node::__set_state(array(
       'mac' => '08:00:27:27:E7:FA',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.207',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100ACF',
    )),
    '00:0C:29:F6:FC:C2' => 
    node::__set_state(array(
       'mac' => '00:0C:29:F6:FC:C2',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.249',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AF9',
    )),
    '20:CF:30:66:56:40' => 
    node::__set_state(array(
       'mac' => '20:CF:30:66:56:40',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.236',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AEC',
    )),
    '00:0C:29:C3:74:BD' => 
    node::__set_state(array(
       'mac' => '00:0C:29:C3:74:BD',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.205',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100ACD',
    )),
    '00:0C:29:CD:59:07' => 
    node::__set_state(array(
       'mac' => '00:0C:29:CD:59:07',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.246',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AF6',
    )),
    'DC:0E:F9:82:D5:F7' => 
    node::__set_state(array(
       'mac' => 'DC:0E:F9:82:D5:F7',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.208',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AD0',
    )),
    'DC:0E:A1:1C:8D:A1' => 
    node::__set_state(array(
       'mac' => 'DC:0E:A1:1C:8D:A1',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.223',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100ADF',
    )),
    '00:0C:29:81:61:8C' => 
    node::__set_state(array(
       'mac' => '00:0C:29:81:61:8C',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.106',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100A6A',
    )),
    '00:0C:29:10:47:04' => 
    node::__set_state(array(
       'mac' => '00:0C:29:10:47:04',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.240',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AF0',
    )),
    'DC:0E:7A:C7:47:28' => 
    node::__set_state(array(
       'mac' => 'DC:0E:7A:C7:47:28',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.212',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AD4',
    )),
    '00:0C:29:DA:A7:5F' => 
    node::__set_state(array(
       'mac' => '00:0C:29:DA:A7:5F',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.222',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100ADE',
    )),
    'FE:0E:BB:BB:01:04' => 
    node::__set_state(array(
       'mac' => 'FE:0E:BB:BB:01:04',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.220',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100ADC',
    )),
    '08:00:27:75:4D:02' => 
    node::__set_state(array(
       'mac' => '08:00:27:75:4D:02',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.103',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100A67',
    )),
    'DC:0E:BB:BB:01:A1' => 
    node::__set_state(array(
       'mac' => 'DC:0E:BB:BB:01:A1',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.151',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100A97',
    )),
    '00:18:8B:80:0C:82' => 
    node::__set_state(array(
       'mac' => '00:18:8B:80:0C:82',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.65',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100A41',
    )),
    '00:E0:12:BC:76:99' => 
    node::__set_state(array(
       'mac' => '00:E0:12:BC:76:99',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.225',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AE1',
    )),
    '00:0C:29:B7:89:45' => 
    node::__set_state(array(
       'mac' => '00:0C:29:B7:89:45',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.231',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AE7',
    )),
    '00:0C:29:64:5F:F4' => 
    node::__set_state(array(
       'mac' => '00:0C:29:64:5F:F4',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.221',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100ADD',
    )),
    '52:54:00:37:10:69' => 
    node::__set_state(array(
       'mac' => '52:54:00:37:10:69',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.241',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AF1',
    )),
    '52:54:00:5B:9B:84' => 
    node::__set_state(array(
       'mac' => '52:54:00:5B:9B:84',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.235',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AEB',
    )),
    '00:0C:29:30:37:C8' => 
    node::__set_state(array(
       'mac' => '00:0C:29:30:37:C8',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.209',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AD1',
    )),
    '14:DA:E9:F0:23:14' => 
    node::__set_state(array(
       'mac' => '14:DA:E9:F0:23:14',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.228',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AE4',
    )),
    'DC:0E:BB:BB:01:A2' => 
    node::__set_state(array(
       'mac' => 'DC:0E:BB:BB:01:A2',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.152',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100A98',
    )),
    '5C:F3:FC:00:B0:FF' => 
    node::__set_state(array(
       'mac' => '5C:F3:FC:00:B0:FF',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.219',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100ADB',
    )),
    '00:0C:29:3E:84:F1' => 
    node::__set_state(array(
       'mac' => '00:0C:29:3E:84:F1',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.201',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AC9',
    )),
    '08:00:27:E6:95:E6' => 
    node::__set_state(array(
       'mac' => '08:00:27:E6:95:E6',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.237',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AED',
    )),
    'F0:4D:A2:83:3A:44' => 
    node::__set_state(array(
       'mac' => 'F0:4D:A2:83:3A:44',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.232',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AE8',
    )),
    '00:0C:29:EA:4D:18' => 
    node::__set_state(array(
       'mac' => '00:0C:29:EA:4D:18',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.101',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100A65',
    )),
    '52:54:00:32:63:BA' => 
    node::__set_state(array(
       'mac' => '52:54:00:32:63:BA',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.216',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AD8',
    )),
    'DC:0E:E9:36:49:0B' => 
    node::__set_state(array(
       'mac' => 'DC:0E:E9:36:49:0B',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.206',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100ACE',
    )),
    'B8:AC:6F:41:F6:D3' => 
    node::__set_state(array(
       'mac' => 'B8:AC:6F:41:F6:D3',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.204',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100ACC',
    )),
    'BC:30:5B:CB:A8:27' => 
    node::__set_state(array(
       'mac' => 'BC:30:5B:CB:A8:27',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.100',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100A64',
    )),
    '00:1D:09:21:18:12' => 
    node::__set_state(array(
       'mac' => '00:1D:09:21:18:12',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.230',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AE6',
    )),
    '00:0C:29:88:A5:F2' => 
    node::__set_state(array(
       'mac' => '00:0C:29:88:A5:F2',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.239',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AEF',
    )),
    '00:0C:29:D5:D3:BC' => 
    node::__set_state(array(
       'mac' => '00:0C:29:D5:D3:BC',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.109',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100A6D',
    )),
    '00:24:7E:6F:93:F1' => 
    node::__set_state(array(
       'mac' => '00:24:7E:6F:93:F1',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.102',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100A66',
    )),
    '00:0C:29:D2:4D:17' => 
    node::__set_state(array(
       'mac' => '00:0C:29:D2:4D:17',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.105',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100A69',
    )),
    '08:00:27:F2:F1:37' => 
    node::__set_state(array(
       'mac' => '08:00:27:F2:F1:37',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.217',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AD9',
    )),
    'DC:0E:BB:BB:03:01' => 
    node::__set_state(array(
       'mac' => 'DC:0E:BB:BB:03:01',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.244',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AF4',
    )),
    'DC:0E:BB:BB:01:A0' => 
    node::__set_state(array(
       'mac' => 'DC:0E:BB:BB:01:A0',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.150',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100A96',
    )),
    'DC:0E:83:E8:96:B8' => 
    node::__set_state(array(
       'mac' => 'DC:0E:83:E8:96:B8',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.215',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AD7',
    )),
    '00:0C:29:C3:74:B3' => 
    node::__set_state(array(
       'mac' => '00:0C:29:C3:74:B3',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.214',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AD6',
    )),
    '52:54:00:D7:41:DA' => 
    node::__set_state(array(
       'mac' => '52:54:00:D7:41:DA',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.233',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AE9',
    )),
    '00:E0:12:B1:3F:98' => 
    node::__set_state(array(
       'mac' => '00:E0:12:B1:3F:98',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.224',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AE0',
    )),
    '00:0C:29:F2:C7:52' => 
    node::__set_state(array(
       'mac' => '00:0C:29:F2:C7:52',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.202',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100ACA',
    )),
    '5C:F3:FC:00:B0:3F' => 
    node::__set_state(array(
       'mac' => '5C:F3:FC:00:B0:3F',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.218',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100ADA',
    )),
    '00:0C:29:2A:C6:C9' => 
    node::__set_state(array(
       'mac' => '00:0C:29:2A:C6:C9',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => NULL,
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => '00',
    )),
    'F0:4D:A2:83:3E:D3' => 
    node::__set_state(array(
       'mac' => 'F0:4D:A2:83:3E:D3',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => NULL,
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => '00',
    )),
    '0A:B0:6E:D9:B0:4E' => 
    node::__set_state(array(
       'mac' => '0A:B0:6E:D9:B0:4E',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => NULL,
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => '00',
    )),
    '64:27:37:1C:AF:F5' => 
    node::__set_state(array(
       'mac' => '64:27:37:1C:AF:F5',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => NULL,
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => '00',
    )),
    '00:0C:29:2C:7A:0D' => 
    node::__set_state(array(
       'mac' => '00:0C:29:2C:7A:0D',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => NULL,
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => '00',
    )),
    '00:0C:29:EE:EE:EE' => 
    node::__set_state(array(
       'mac' => '00:0C:29:EE:EE:EE',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => NULL,
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => '00',
    )),
    'D0:67:E5:26:F3:38' => 
    node::__set_state(array(
       'mac' => 'D0:67:E5:26:F3:38',
       'active' => true,
       'deny' => false,
       'fixedip' => true,
       'ipaddr' => '172.16.10.250',
       'subnet' => NULL,
       'terminal_default' => true,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => ',',
       'right_default' => true,
       'rights' => ',',
       'filename' => 'AC100AFA',
    )),
  ),
   'leases' => 
  array (
    '00:0c:29:f6:fc:c2' => 
    node::__set_state(array(
       'mac' => '00:0c:29:f6:fc:c2',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.249',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AF9',
    )),
    '00:0c:29:cd:59:07' => 
    node::__set_state(array(
       'mac' => '00:0c:29:cd:59:07',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.246',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AF6',
    )),
    '00:0c:29:77:08:dc' => 
    node::__set_state(array(
       'mac' => '00:0c:29:77:08:dc',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.247',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AF7',
    )),
    'dc:0e:bb:bb:03:01' => 
    node::__set_state(array(
       'mac' => 'dc:0e:bb:bb:03:01',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.244',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AF4',
    )),
    '00:0c:29:88:a5:f2' => 
    node::__set_state(array(
       'mac' => '00:0c:29:88:a5:f2',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.239',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AEF',
    )),
    '00:0c:29:10:47:04' => 
    node::__set_state(array(
       'mac' => '00:0c:29:10:47:04',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.240',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AF0',
    )),
    '52:54:00:37:10:69' => 
    node::__set_state(array(
       'mac' => '52:54:00:37:10:69',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.241',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AF1',
    )),
    '52:54:00:5b:9b:84' => 
    node::__set_state(array(
       'mac' => '52:54:00:5b:9b:84',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.235',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AEB',
    )),
    '20:cf:30:66:56:40' => 
    node::__set_state(array(
       'mac' => '20:cf:30:66:56:40',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.236',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AEC',
    )),
    '08:00:27:e6:95:e6' => 
    node::__set_state(array(
       'mac' => '08:00:27:e6:95:e6',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.237',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AED',
    )),
    '00:0c:29:c3:74:b3' => 
    node::__set_state(array(
       'mac' => '00:0c:29:c3:74:b3',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.214',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AD6',
    )),
    'dc:0e:83:e8:96:b8' => 
    node::__set_state(array(
       'mac' => 'dc:0e:83:e8:96:b8',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.215',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AD7',
    )),
    '52:54:00:32:63:ba' => 
    node::__set_state(array(
       'mac' => '52:54:00:32:63:ba',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.216',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AD8',
    )),
    '08:00:27:f2:f1:37' => 
    node::__set_state(array(
       'mac' => '08:00:27:f2:f1:37',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.217',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AD9',
    )),
    '5c:f3:fc:00:b0:3f' => 
    node::__set_state(array(
       'mac' => '5c:f3:fc:00:b0:3f',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.218',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100ADA',
    )),
    '5c:f3:fc:00:b0:ff' => 
    node::__set_state(array(
       'mac' => '5c:f3:fc:00:b0:ff',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.219',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100ADB',
    )),
    'fe:0e:bb:bb:01:04' => 
    node::__set_state(array(
       'mac' => 'fe:0e:bb:bb:01:04',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.220',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100ADC',
    )),
    '00:0c:29:64:5f:f4' => 
    node::__set_state(array(
       'mac' => '00:0c:29:64:5f:f4',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.221',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100ADD',
    )),
    '00:0c:29:da:a7:5f' => 
    node::__set_state(array(
       'mac' => '00:0c:29:da:a7:5f',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.222',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100ADE',
    )),
    'dc:0e:a1:1c:8d:a1' => 
    node::__set_state(array(
       'mac' => 'dc:0e:a1:1c:8d:a1',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.223',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100ADF',
    )),
    '00:e0:12:b1:3f:98' => 
    node::__set_state(array(
       'mac' => '00:e0:12:b1:3f:98',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.224',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AE0',
    )),
    '00:e0:12:bc:76:99' => 
    node::__set_state(array(
       'mac' => '00:e0:12:bc:76:99',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.225',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AE1',
    )),
    '00:0c:29:e6:5f:0d' => 
    node::__set_state(array(
       'mac' => '00:0c:29:e6:5f:0d',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.226',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AE2',
    )),
    '00:16:3e:5d:c7:9f' => 
    node::__set_state(array(
       'mac' => '00:16:3e:5d:c7:9f',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.227',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AE3',
    )),
    '14:da:e9:f0:23:14' => 
    node::__set_state(array(
       'mac' => '14:da:e9:f0:23:14',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.228',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AE4',
    )),
    '00:19:e0:75:0c:08' => 
    node::__set_state(array(
       'mac' => '00:19:e0:75:0c:08',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.229',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AE5',
    )),
    '00:1d:09:21:18:12' => 
    node::__set_state(array(
       'mac' => '00:1d:09:21:18:12',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.230',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AE6',
    )),
    '00:0c:29:b7:89:45' => 
    node::__set_state(array(
       'mac' => '00:0c:29:b7:89:45',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.231',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AE7',
    )),
    'f0:4d:a2:83:3a:44' => 
    node::__set_state(array(
       'mac' => 'f0:4d:a2:83:3a:44',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.232',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AE8',
    )),
    '52:54:00:d7:41:da' => 
    node::__set_state(array(
       'mac' => '52:54:00:d7:41:da',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.233',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AE9',
    )),
    'dc:0e:7a:c7:47:28' => 
    node::__set_state(array(
       'mac' => 'dc:0e:7a:c7:47:28',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.212',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AD4',
    )),
    'b8:ac:6f:41:f6:d3' => 
    node::__set_state(array(
       'mac' => 'b8:ac:6f:41:f6:d3',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.204',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100ACC',
    )),
    '00:0c:29:c3:74:bd' => 
    node::__set_state(array(
       'mac' => '00:0c:29:c3:74:bd',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.205',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100ACD',
    )),
    'dc:0e:e9:36:49:0b' => 
    node::__set_state(array(
       'mac' => 'dc:0e:e9:36:49:0b',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.206',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100ACE',
    )),
    '08:00:27:27:e7:fa' => 
    node::__set_state(array(
       'mac' => '08:00:27:27:e7:fa',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.207',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100ACF',
    )),
    'dc:0e:f9:82:d5:f7' => 
    node::__set_state(array(
       'mac' => 'dc:0e:f9:82:d5:f7',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.208',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AD0',
    )),
    '00:0c:29:30:37:c8' => 
    node::__set_state(array(
       'mac' => '00:0c:29:30:37:c8',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.209',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AD1',
    )),
    'dc:0e:f9:82:d5:f6' => 
    node::__set_state(array(
       'mac' => 'dc:0e:f9:82:d5:f6',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.210',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AD2',
    )),
    '52:54:00:7e:3c:07' => 
    node::__set_state(array(
       'mac' => '52:54:00:7e:3c:07',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.200',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AC8',
    )),
    '00:0c:29:3e:84:f1' => 
    node::__set_state(array(
       'mac' => '00:0c:29:3e:84:f1',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.201',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AC9',
    )),
    '00:0c:29:f2:c7:52' => 
    node::__set_state(array(
       'mac' => '00:0c:29:f2:c7:52',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.202',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100ACA',
    )),
    'dc:0e:bb:bb:01:a0' => 
    node::__set_state(array(
       'mac' => 'dc:0e:bb:bb:01:a0',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.150',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100A96',
    )),
    'dc:0e:bb:bb:01:a1' => 
    node::__set_state(array(
       'mac' => 'dc:0e:bb:bb:01:a1',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.151',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100A97',
    )),
    'dc:0e:bb:bb:01:a2' => 
    node::__set_state(array(
       'mac' => 'dc:0e:bb:bb:01:a2',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.152',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100A98',
    )),
    '00:0c:29:dc:b8:85' => 
    node::__set_state(array(
       'mac' => '00:0c:29:dc:b8:85',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.108',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100A6C',
    )),
    '00:0c:29:d5:d3:bc' => 
    node::__set_state(array(
       'mac' => '00:0c:29:d5:d3:bc',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.109',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100A6D',
    )),
    'bc:30:5b:cb:a8:27' => 
    node::__set_state(array(
       'mac' => 'bc:30:5b:cb:a8:27',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.100',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100A64',
    )),
    '00:0c:29:ea:4d:18' => 
    node::__set_state(array(
       'mac' => '00:0c:29:ea:4d:18',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.101',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100A65',
    )),
    '00:24:7e:6f:93:f1' => 
    node::__set_state(array(
       'mac' => '00:24:7e:6f:93:f1',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.102',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100A66',
    )),
    '08:00:27:75:4d:02' => 
    node::__set_state(array(
       'mac' => '08:00:27:75:4d:02',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.103',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100A67',
    )),
    'dc:0e:bb:bb:01:08' => 
    node::__set_state(array(
       'mac' => 'dc:0e:bb:bb:01:08',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.104',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100A68',
    )),
    '00:0c:29:d2:4d:17' => 
    node::__set_state(array(
       'mac' => '00:0c:29:d2:4d:17',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.105',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100A69',
    )),
    '00:0c:29:81:61:8c' => 
    node::__set_state(array(
       'mac' => '00:0c:29:81:61:8c',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.106',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100A6A',
    )),
    '00:18:8b:80:0c:82' => 
    node::__set_state(array(
       'mac' => '00:18:8b:80:0c:82',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.65',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100A41',
    )),
    'd0:67:e5:26:f3:38' => 
    node::__set_state(array(
       'mac' => 'd0:67:e5:26:f3:38',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.250',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AFA',
    )),
    'c8:0a:a9:80:70:ee' => 
    node::__set_state(array(
       'mac' => 'c8:0a:a9:80:70:ee',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.248',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AF8',
    )),
    'bc:30:5b:cb:a8:72' => 
    node::__set_state(array(
       'mac' => 'bc:30:5b:cb:a8:72',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.245',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AF5',
    )),
    '00:25:b3:5a:98:2e' => 
    node::__set_state(array(
       'mac' => '00:25:b3:5a:98:2e',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.242',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AF2',
    )),
    '50:e5:49:36:11:16' => 
    node::__set_state(array(
       'mac' => '50:e5:49:36:11:16',
       'active' => NULL,
       'deny' => NULL,
       'fixedip' => NULL,
       'ipaddr' => '172.16.10.243',
       'subnet' => NULL,
       'terminal_default' => NULL,
       'say' => NULL,
       'timeout' => NULL,
       'default' => NULL,
       'allowchoose' => NULL,
       'labels' => NULL,
       'right_default' => NULL,
       'rights' => NULL,
       'filename' => 'AC100AF3',
    )),
  ),
   'right_prefix' => ';配置说明
;以;开始的行是注释行
;每行描述一个用户的信息,格式如下:
;username:password,权限1,权限2,权限3,权限4,....
;用户名和密码注意大小写,头部和尾部的空格和tab会被忽略,注意不要出现同名用户
;权限是用数字来表达其中,1.表示延时港股，2.表示实时港股,3为经济通新闻(默认所有用户有实时港股权限)，4.表示……，5.表示L2行情
;yym314:password,2,3	表示yym314这个用户的密码是password,他有2和3权限
;bird:password				表示bird这个用户的密码是password,他有默认的2权限
;kun:password,3				表示kun这个用户的密码是password,他有默认的2权限和指定的3权限',
   'right_suffix' => NULL,
   'defaultrights' => ',0,',
   'unknownrights' => NULL,
   'originmac' => 
  array (
    '00:0C:29:42:AB:8E' => '172.16.10.12',
    '00:16:3E:5D:C7:9F' => '172.16.10.227',
    '00:0C:29:77:08:DC' => '172.16.10.247',
    'DC:0E:F9:82:D5:F6' => '172.16.10.210',
    'DC:0E:BB:BB:01:08' => '172.16.10.104',
    '52:54:00:7E:3C:07' => '172.16.10.200',
    '00:0C:29:DC:B8:85' => '172.16.10.108',
    '00:19:E0:75:0C:08' => '172.16.10.229',
    '00:0C:29:E6:5F:0D' => '172.16.10.226',
    '08:00:27:27:E7:FA' => '172.16.10.207',
    '00:0C:29:F6:FC:C2' => '172.16.10.249',
    '20:CF:30:66:56:40' => '172.16.10.236',
    '00:0C:29:C3:74:BD' => '172.16.10.205',
    '00:0C:29:CD:59:07' => '172.16.10.246',
    'DC:0E:F9:82:D5:F7' => '172.16.10.208',
    'DC:0E:A1:1C:8D:A1' => '172.16.10.223',
    '00:0C:29:81:61:8C' => '172.16.10.106',
    '00:0C:29:10:47:04' => '172.16.10.240',
    'DC:0E:7A:C7:47:28' => '172.16.10.212',
    '00:0C:29:DA:A7:5F' => '172.16.10.222',
    'FE:0E:BB:BB:01:04' => '172.16.10.220',
    '08:00:27:75:4D:02' => '172.16.10.103',
    'DC:0E:BB:BB:01:A1' => '172.16.10.151',
    '00:18:8B:80:0C:82' => '172.16.10.65',
    '00:E0:12:BC:76:99' => '172.16.10.225',
    '00:0C:29:B7:89:45' => '172.16.10.231',
    '00:0C:29:64:5F:F4' => '172.16.10.221',
    '52:54:00:37:10:69' => '172.16.10.241',
    '52:54:00:5B:9B:84' => '172.16.10.235',
    '00:0C:29:30:37:C8' => '172.16.10.209',
    '14:DA:E9:F0:23:14' => '172.16.10.228',
    'DC:0E:BB:BB:01:A2' => '172.16.10.152',
    '5C:F3:FC:00:B0:FF' => '172.16.10.219',
    '00:0C:29:3E:84:F1' => '172.16.10.201',
    '08:00:27:E6:95:E6' => '172.16.10.237',
    'F0:4D:A2:83:3A:44' => '172.16.10.232',
    '00:0C:29:EA:4D:18' => '172.16.10.101',
    '52:54:00:32:63:BA' => '172.16.10.216',
    'DC:0E:E9:36:49:0B' => '172.16.10.206',
    'B8:AC:6F:41:F6:D3' => '172.16.10.204',
    'BC:30:5B:CB:A8:27' => '172.16.10.100',
    '00:1D:09:21:18:12' => '172.16.10.230',
    '00:0C:29:88:A5:F2' => '172.16.10.239',
    '00:0C:29:D5:D3:BC' => '172.16.10.109',
    '00:24:7E:6F:93:F1' => '172.16.10.102',
    '00:0C:29:D2:4D:17' => '172.16.10.105',
    '08:00:27:F2:F1:37' => '172.16.10.217',
    'DC:0E:BB:BB:03:01' => '172.16.10.244',
    'DC:0E:BB:BB:01:A0' => '172.16.10.150',
    'DC:0E:83:E8:96:B8' => '172.16.10.215',
    '00:0C:29:C3:74:B3' => '172.16.10.214',
    '52:54:00:D7:41:DA' => '172.16.10.233',
    '00:E0:12:B1:3F:98' => '172.16.10.224',
    '00:0C:29:F2:C7:52' => '172.16.10.202',
    '5C:F3:FC:00:B0:3F' => '172.16.10.218',
    '00:0C:29:2A:C6:C9' => NULL,
    'F0:4D:A2:83:3E:D3' => NULL,
    '0A:B0:6E:D9:B0:4E' => NULL,
    '64:27:37:1C:AF:F5' => NULL,
    '00:0C:29:2C:7A:0D' => NULL,
    '00:0C:29:EE:EE:EE' => NULL,
    'D0:67:E5:26:F3:38' => '172.16.10.250',
  ),
));

//print_r($a);
var_export($a);
?>

