<?
$summary=array(
"CONFIG_HAPPYMEAL"=>"Sun Happy Meal 10/100baseT Íø¿¨",
"CONFIG_SUNGEM "=>"  Sun GEM Íø¿¨",
"CONFIG_CASSINI"=>" Sun Cassini Íø¿¨   ",
"CONFIG_VORTEX"=>" 3com VORTEX",
"CONFIG_TYPHOON"=>" 3cr990 series \"Typhoon\" Íø¿¨    ",
"CONFIG_DE2104X"=>"  Early DECchip Tulip (dc2104x) PCI Íø¿¨ ",
"CONFIG_DE4X5"=>" Generic DECchip & DIGITAL EtherWORKS PCI/EISA        ",
"CONFIG_WINBOND_840"=>"Winbond W89c840 Ethernet Íø¿¨ ",
"CONFIG_DM9102"=>" Davicom DM910x/DM980x Íø¿¨ ",
"CONFIG_ULI526X"=>"ULi M526x controller Íø¿¨  ",
"CONFIG_HP100"=>" HP 10/100VG PCLAN (ISA, EISA, PCI) Íø¿¨         ",
"CONFIG_PCNET32"=>" AMD PCnet32 PCI Íø¿¨     ",
"CONFIG_AMD8111_ETH"=>" AMD 8111 (new PCI lance) Íø¿¨ ",
"CONFIG_ADAPTEC_STARFIRE"=>"Adaptec Starfire/DuraLAN Íø¿¨",
"CONFIG_B44"=>" Broadcom 4400 ethernet Íø¿¨     ",
"CONFIG_FORCEDETH"=>"nForce Ethernet Íø¿¨      ",
"CONFIG_DGRS"=>" Digi Intl. RightSwitch SE-X Íø¿¨    ",
"CONFIG_EEPRO100"=>"  EtherExpressPro/100 Íø¿¨ (eepro100, original Becker driver)     ",
"CONFIG_E100"=>" Intel(R) PRO/100+ Íø¿¨      ",
"CONFIG_FEALNX"=>" Myson MTD-8xx PCI Ethernet Íø¿¨      ",
"CONFIG_NATSEMI "=>" National Semiconductor DP8381x series PCI Ethernet Íø¿¨       ",
"CONFIG_NE2K_PCI"=>"  PCI NE2000 and clones Íø¿¨ (see help)   ",
"CONFIG_8139CP"=>" RealTek RTL-8139 C+ PCI Fast Ethernet Adapter Íø¿¨ (EXPERIMENTAL)    ",
"CONFIG_8139TOO"=>" RealTek RTL-8129/8130/8139 PCI Fast Ethernet Adapter Íø¿¨                                    ",
"CONFIG_SIS900"=>"  SiS 900/7016 PCI Fast Ethernet Adapter Íø¿¨     ",
"CONFIG_EPIC100"=>" SMC EtherPower II ",
"CONFIG_SUNDANCE"=>" Sundance Alta Íø¿¨          ",
"CONFIG_TLAN"=>"   TI ThunderLAN Íø¿¨     ",
"CONFIG_VIA_RHINE"=>" VIA Rhine Íø¿¨",
"CONFIG_SC92031"=>" Silan SC92031 PCI Fast Ethernet Adapter driver (EXPERIMENTAL) ",
#1000",
"CONFIG_ACENIC"=>"Alteon AceNIC/3Com 3C985/NetGear GA620 Gigabit Íø¿¨      ",
"CONFIG_DL2K"=>"  D-Link DL2000-based Gigabit Ethernet Íø¿¨       ",
"CONFIG_E1000"=>" Intel(R) PRO/1000 Gigabit Ethernet Íø¿¨               ",
"CONFIG_R8168"=>" Realtek 8111B/8111C Gigabit Ethernet Íø¿¨  ",
"CONFIG_R8101"=>"  Realtek 8101/8102/8103 Gigabit Ethernet Íø¿¨       ",
"CONFIG_NS83820 "=>"  National Semiconductor DP83820 Íø¿¨   ",
"CONFIG_HAMACHI "=>"  Packet Engines Hamachi GNIC-II Íø¿¨    ",
"CONFIG_YELLOWFIN "=>" Packet Engines Yellowfin Gigabit-NIC Íø¿¨ (EXPERIMENTAL)              ",
"CONFIG_R8169 "=>"  Realtek 8169 gigabit ethernet Íø¿¨        ",
"CONFIG_SIS190 "=>"   SiS190/SiS191 gigabit ethernet Íø¿¨    ",
"CONFIG_SKGE "=>"  New SysKonnect GigaEthernet Íø¿¨     ",
"CONFIG_SKY2 "=>"   SysKonnect Yukon2 Íø¿¨",
"CONFIG_SK98LIN "=>"  Marvell Yukon Chipset / SysKonnect SK-98xx Íø¿¨ (",
"CONFIG_VIA_VELOCITY "=>" VIA Velocity Íø¿¨  ",
"CONFIG_TIGON3 "=>" Broadcom Tigon3 Íø¿¨   ",
"CONFIG_BNX2 "=>"  Broadcom NetXtremeII Íø¿¨    ",
"CONFIG_QLA3XXX "=>"  QLogic QLA3XXX Network Driver Íø¿¨          ",
"CONFIG_ATL1 "=>" Attansic L1 Gigabit Ethernet Íø¿¨ (EXPERIMENTAL)    ",
#10000",
"CONFIG_CHELSIO_T1 "=>"  Chelsio 10Gb Ethernet Íø¿¨  ",
"CONFIG_CHELSIO_T3 "=>"  Chelsio Communications T3 10Gb Ethernet Íø¿¨         ",
"CONFIG_IXGB "=>"   Intel(R) PRO/10GbE Íø¿¨      ",
"CONFIG_S2IO "=>"  S2IO 10Gbe XFrame NIC       ",
"CONFIG_MYRI10GE "=>" Myricom Myri-10G Ethernet Íø¿¨    ",
"CONFIG_NETXEN_NIC "=>" NetXen Multi port (1/10) Gigabit Ethernet NIC   "
);

foreach ($summary as $net=>$summary)
{
	echo  $net."\t".$summary."\n";
}
?>
